from enum import Enum


class BTReleaseStage(str, Enum):
    APPROVERS_METADATA_STARTED = "APPROVERS_METADATA_STARTED"
    APPROVERS_RECORDED = "APPROVERS_RECORDED"
    CREATE_RELEASE_PACKAGE_INFO = "CREATE_RELEASE_PACKAGE_INFO"
    HANDLE_FROZEN_PACKAGE = "HANDLE_FROZEN_PACKAGE"
    POSTSUBMIT_FANOUT_COMPLETED = "POSTSUBMIT_FANOUT_COMPLETED"
    POSTSUBMIT_FANOUT_STARTED = "POSTSUBMIT_FANOUT_STARTED"
    PRETRANSITION_MUTATIONS_COMMITTED = "PRETRANSITION_MUTATIONS_COMMITTED"
    PRETRANSITION_MUTATIONS_STARTED = "PRETRANSITION_MUTATIONS_STARTED"
    PRETRANSITION_VALIDATION_STARTED = "PRETRANSITION_VALIDATION_STARTED"
    RELEASE_PACKAGE_INITIALIZED = "RELEASE_PACKAGE_INITIALIZED"
    RELEASE_PACKAGE_METADATA_UPDATE = "RELEASE_PACKAGE_METADATA_UPDATE"
    RELEASE_PACKAGE_UPDATE = "RELEASE_PACKAGE_UPDATE"
    RELEASE_PACKAGE_VALIDATION = "RELEASE_PACKAGE_VALIDATION"
    UPDATE_PACKAGE_PROPERTIES = "UPDATE_PACKAGE_PROPERTIES"
    WORKFLOW_AUDIT_COMPLETED = "WORKFLOW_AUDIT_COMPLETED"
    WORKFLOW_STATE_SAVED = "WORKFLOW_STATE_SAVED"
    WORKFLOW_TRANSITION_STARTED = "WORKFLOW_TRANSITION_STARTED"

    def __str__(self) -> str:
        return str(self.value)
