from enum import Enum


class GBTDebugEntityColor(str, Enum):
    BLACK = "BLACK"
    BLUE = "BLUE"
    CYAN = "CYAN"
    FEATURE_DEBUG = "FEATURE_DEBUG"
    FEATURE_ERROR = "FEATURE_ERROR"
    GREEN = "GREEN"
    MAGENTA = "MAGENTA"
    ORANGE = "ORANGE"
    RED = "RED"
    TRANSLUCENT_BLACK = "TRANSLUCENT_BLACK"
    TRANSLUCENT_BLUE = "TRANSLUCENT_BLUE"
    TRANSLUCENT_CYAN = "TRANSLUCENT_CYAN"
    TRANSLUCENT_GREEN = "TRANSLUCENT_GREEN"
    TRANSLUCENT_MAGENTA = "TRANSLUCENT_MAGENTA"
    TRANSLUCENT_ORANGE = "TRANSLUCENT_ORANGE"
    TRANSLUCENT_PURPLE = "TRANSLUCENT_PURPLE"
    TRANSLUCENT_RED = "TRANSLUCENT_RED"
    TRANSLUCENT_YELLOW = "TRANSLUCENT_YELLOW"
    UNKNOWN = "UNKNOWN"
    YELLOW = "YELLOW"

    def __str__(self) -> str:
        return str(self.value)
