from enum import Enum


class GBTMetadataOverrideStatusType(str, Enum):
    COMPUTED_WITH_NO_OVERRIDES = "COMPUTED_WITH_NO_OVERRIDES"
    COMPUTED_WITH_OVERRIDES = "COMPUTED_WITH_OVERRIDES"
    COMPUTED_WITH_SUBASSEMBLY_OVERRIDES = "COMPUTED_WITH_SUBASSEMBLY_OVERRIDES"
    OVERRIDDEN = "OVERRIDDEN"
    PROPERTY_NOT_COMPUTED = "PROPERTY_NOT_COMPUTED"
    UNKNOWN = "UNKNOWN"

    def __str__(self) -> str:
        return str(self.value)
