from enum import Enum


class GBTPreProcessParasolidOption(str, Enum):
    NO_PRE_PROCESSING = "NO_PRE_PROCESSING"
    UNKNOWN = "UNKNOWN"
    USE_BODYSHOP_PRE_PROCESSING = "USE_BODYSHOP_PRE_PROCESSING"
    USE_BODYSHOP_PRE_PROCESSING_ADVANCED = "USE_BODYSHOP_PRE_PROCESSING_ADVANCED"
    USE_BODYSHOP_PRE_PROCESSING_ADVANCED_WITH_SURFS_TO_BSURFS_CONVERTING = (
        "USE_BODYSHOP_PRE_PROCESSING_ADVANCED_WITH_SURFS_TO_BSURFS_CONVERTING"
    )
    USE_TRANSLATOR_PRE_PROCESSING = "USE_TRANSLATOR_PRE_PROCESSING"

    def __str__(self) -> str:
        return str(self.value)
