from enum import Enum


class GBTGraphicsBufferTarget(str, Enum):
    ARRAY_BUFFER = "ARRAY_BUFFER"
    ELEMENT_ARRAY_BUFFER = "ELEMENT_ARRAY_BUFFER"
    ENTITY_PART_INDEX_BUFFER = "ENTITY_PART_INDEX_BUFFER"
    ENTITY_RANGE_BUFFER = "ENTITY_RANGE_BUFFER"
    SKETCH_ENTITY_PARTID_INDEX_COUNT_ENTITY_COUNT_BUFFER = "SKETCH_ENTITY_PARTID_INDEX_COUNT_ENTITY_COUNT_BUFFER"
    UNKNOWN = "UNKNOWN"

    def __str__(self) -> str:
        return str(self.value)
