from enum import Enum


class GBTGTolConstraintType(str, Enum):
    ANGULARITY = "ANGULARITY"
    CIRCULAR_RUNOUT = "CIRCULAR_RUNOUT"
    CONCENTRICITY = "CONCENTRICITY"
    CYLINDRICITY = "CYLINDRICITY"
    FLATNESS = "FLATNESS"
    PARALLELISM = "PARALLELISM"
    PERPENDICULARITY = "PERPENDICULARITY"
    PROFILE_LINE = "PROFILE_LINE"
    PROFILE_SURFACE = "PROFILE_SURFACE"
    ROUNDNESS = "ROUNDNESS"
    STRAIGHTNESS = "STRAIGHTNESS"
    SYMMETRY = "SYMMETRY"
    TOTAL_RUNOUT = "TOTAL_RUNOUT"
    TRUE_POSITION = "TRUE_POSITION"
    UNKNOWN = "UNKNOWN"

    def __str__(self) -> str:
        return str(self.value)
